wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.4
    start_time: 1635475233
    t:
      4: 3.9.4
      5: 0.12.6
      8:
      - 4
      - 5
