wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 4.12.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.4
    start_time: 1635475079
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 1
      4: 3.9.4
      5: 0.12.6
      6: 4.12.0
      8:
      - 4
      - 5
